# Distribution Day V3
default_index: "000985"
default_date_range:
  start: "2024-01-01"
  end: "2026-12-31"

cards:
  card1:
    enabled: True
    decline: -0.1
    vol: 1.00
  card2:
    enabled: True
    chg_min: -0.3
    chg_max: 0.2
    surge: 0.5
    vol: 1.0
    shadow: 1.5
  card3:
    enabled: True
    surge: 0.5
    vol: 1.0
    shadow: 1.5
    midpt: 50
  card4:
    enabled: True
    decline: -1.5
    vol: 0.98
